baseURL = "https://chry-santhemum.github.io/website/"
languageCode = "en-us"
title = "Home"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Hi!"
Content = "I am Zifan Wang (王子凡) and I often go by Atticus. I'm an MIT '26 majoring in (pure) math, with frivolous interests in music, writing, physics, and computer science."

[[params.socialIcons]]
name = "email"
url = "mailto:atticusw@mit.edu"


[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 50

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 60