baseURL = "https://chry-santhemum.github.io/website/"
languageCode = "en-us"
title = "Atticus Wang"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Hey! I'm Atticus."
Content = """&#8201;

_Look at the sky. Ask yourself: \"Has the sheep eaten the flower or not?\" And you will see how everything changes..._

&#8201;

&#11013; &#11013; [will](https://willhath.com/) &#11013; &#11013; (my friends!) &#10145; &#10145; [shreya](https://smog.ink/) &#10145; &#10145;"""


[[params.socialIcons]]
name = "email"
url = "mailto:atticusw@mit.edu"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/zifan.wang.524/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/tweetfkingtweet"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 50

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 60