baseURL = "https://chry-santhemum.github.io/website/"
languageCode = "en-us"
title = "Atticus Wang"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true

[params.homeInfoParams]
Title = "Hey! I'm Atticus."
Content = """&#8201;

[caches]
  [caches.images]
    dir = ':cacheDir/images'

![cezanne](/website/images/cezanne.jpg)"""


[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "notes"
name = "Notes"
url = "/notes/"
weight = 30

[[menu.main]]
identifier = "seminar"
name = "Seminar"
url = "/seminar/"
weight = 60