baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Atticus Wang - Home'
theme = 'PaperMod'
[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"
