baseURL = "https://chry-santhemum.github.io/website/"
languageCode = "en-us"
title = "Atticus Wang"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true

[params.homeInfoParams]
Title = "Hey! I'm Atticus."
Content = """&#8201;

As for me, nothing in the universe can be the same if somewhere, no one knows where, a sheep we never saw has or has not eaten a rose... Look up at the sky. Ask yourself: \"Has the sheep eaten the flower or not?\" And you will see how everything changes...

&#8201;

![cezanne](/website/images/cezanne.jpg)

&#8201;

&#11013; &#11013; [Will](https://willhath.com/) &#11013; &#11013; Friends &#10145; &#10145; [Shreya](https://smog.ink/) &#10145; &#10145;"""


[[params.socialIcons]]
name = "email"
url = "mailto:atticusw@mit.edu"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/zifan.wang.524/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/tweetfkingtweet"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 50

[[menu.main]]
identifier = "seminar"
name = "Seminar"
url = "/seminar/"
weight = 55

[[menu.main]]
identifier = "notes"
name = "Notes"
url = "/notes/"
weight = 60