baseURL = "https://chry-santhemum.github.io/website/"
languageCode = "en-us"
title = "Home"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Homepage of Atticus"
Content = "I am Zifan Wang (王子凡) and I often go by Atticus. I am an MIT undergrad majoring in (pure) math and interested in physics, poetry, writing, music, and theoretical computer science."

[[params.socialIcons]]
name = "email"
url = "mailto:atticusw@mit.edu"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/zifan.wang.524/"


[[menu.main]]
identifier = "resume"
name = "Résumé"
url = "/resume/"
weight = 50

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 60